module.exports = {
	semi: true,
	singleQuote: false,
	trailingComma: "all",
	printWidth: 100,
	useTabs: true,
	plugins: ["prettier-plugin-tailwindcss"],
	tailwindConfig: "./tailwind.config.ts",
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"^(next/(.*)$)|^(next$)",
		"<THIRD_PARTY_MODULES>",
		"",
		"^types$",
		"^@/types/(.*)$",
		"^@/config/(.*)$",
		"^@/lib/(.*)$",
		"^@/hooks/(.*)$",
		"^@/ui/(.*)$",
		"^@/registry/(.*)$",
		"^@/styles/(.*)$",
		"^@/app/(.*)$",
		"",
		"^[./]",
	],
};
